### ISSUE TITLE
Your pgq_ext extension right now  not work

### ISSUE THREAD

**Issue by Ivanov-Anton** [pgq/pgq-ext#1]
ubuntu bionic
ubuntu xenial
debian stretch

now to compile a working extension I need to go back one commit

`create extension pgq_ext;`
`ERROR:  extension "pgq_ext" has no installation script nor update path for version "3.1"`

**Comment by Ivanov-Anton** [comment]
For ease of installation, I would like to install the extension like this: apt install postgresql-11-pgq_ext

**Comment by markokr** [comment]
Seems there was still mismatch in versioning.

Could you try install from master?

**Comment by Ivanov-Anton** [comment]
The error was successfully fixed.
Please consider installing through apt
