### ISSUE TITLE
Incorrect tag - v3.3.1

### ISSUE THREAD

**Issue by crunchyjohn** [pgq/pgq-ext#2]
Hello!

The v3.3.1 tag is actually named incorrectly and should be modified.  It's actually supposed to be v3.1.1.
This caused issues because the v3.3.1 tag looks "newer" than the v3.3 tag, which isn't true based on date stamps and content.  Building the v3.3.1 tag actually gives you a 3.1.1 build.

Additionally, if you look at this link:
https://github.com/pgq/pgq-ext/releases/tag/v3.3.1
you will see that this asset is 3.1.1:
[pgq_ext-3.1.1.tar.gz](https://github.com/pgq/pgq-ext/releases/download/v3.3.1/pgq_ext-3.1.1.tar.gz)

We thought it might be helpful to suggest renaming this tag to prevent confusion, especially since v3.3 is the "latest and greatest".

**Comment by markokr** [comment]
Thank you!

Fixed the tag.
